
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Migrations require a direct (non-pooled) connection.
    // DIRECT_URL bypasses PgBouncer (port 6543) which rejects DDL via
    // prepared statements; direct connections (port 5432) support full DDL.
    url: env("DIRECT_URL"),
  },
});
